name: keepalive_kyb

on:
  schedule:
    - cron: '14 0 */6 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Random Cron
      uses: grbnb/random-workflow-cron@v2
      with:
        github_token: ${{ secrets.PAT }}  # 务必添加Personal Access Token密钥 没有请自行创建 https://github.com/settings/tokens/new
        keep_history: true
        time_zone: "UTC+8"
        interval_count: 1
        cron_dmw: "*/6 * *"

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Run Keepalive
      run: python3 koyeb.py
      env:
        KOY_EB: ${{ secrets.KOY_EB }}
        PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}  ## 填写对应的平台通知变量名[此处使用pushplus推送]，若需要多平台同时推送，请按此格式填写多个平台对应的变量名即可
